# -*- coding: utf-8 -*-
"""Mnist Dataset

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rNRhU-ZfCEDs9cQdNJGgLAIu4Qntre6H
"""
import pandas as pd
import matplotlib as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
data = keras.datasets.mnist
df=data.load_data()
(x_train,y_train),(x_test,y_test)=df
X_train_flat = x_train.reshape(-1, 28*28)
X_test_flat = x_test.reshape(-1, 28*28)
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
"""Importing Dataset

"""
model=Sequential([
    Dense(units=10,input_shape=(784,),activation="sigmoid")
]) 
model.compile(
    optimizer='adam',loss='sparse_categorical_crossentropy',
    metrics='accuracy'
)
X_train_flat[0].shape
model.fit(X_train_flat,y_train,epochs=10)
y_pred=model.predict(X_test_flat)
model.evaluate(X_test_flat,y_test)
